### ISSUE TITLE
If i need save or update config file how i can do it?

### ISSUE THREAD

**Issue by visteras** [ElderResearch/ssc#9]
If i need save or update config file how i can do it? Or only read?...

**Comment by metasim** [comment]
Are asking how you reread the a config file that's changed on disk?

**Comment by visteras** [comment]
I do not understand .. why reread? For what? I need to write the new value, and re-read it then it is not necessary, though possible.

**Comment by visteras** [comment]
Let me explain, I wanted to see if any of the parameters in the configuration is not - he added in the config file automatically. But now I understand that this can be done is used merge and overwriting the main config file after starting the application.
I apologize
